- appmgr/Cargo.lock
- appmgr/Cargo.toml
- appmgr/src/tor.rs
this might break everything. It deletes the hostname (but not the key) on app install, before reloading tor.
> appmgr: handle tor address version change

- ui/src/app/pages/server-routes/server-specs/server-specs.page.html
This PR adds a copy to clipboard button for the Embassy's `Tor Address` found under server specs.
I did not see an associated issue but there was a `TODO:` in the code.
Note: This is my first PR. I reviewed the contributing docs but apologies if I've missed anything.
> ui: copy button for tor address spec

- ui/src/app/pages/apps-routes/app-available-show/app-available-show.page.html
Adding a button for "Go to Service" from a marketplace listing.
Reference: #188 
Note: `[routerLink]` looked like the way routing over to the services page would be handled but if there's a more appropriate way, let me know.
> ui: add go to service button on marketplace listing

- appmgr/src/nginx-standard.conf.template
- appmgr/src/nginx.conf.template
Update nginx templates with `client_max_body_size 0;`, to eliminate "file too large" errors while uploading to filebrowser.
> Nginx: allow infinite body sizes

- appmgr/src/nginx-standard.conf.template
- appmgr/src/nginx.conf.template
- appmgr/src/version/v0_2_12.rs
Disables both request and response buffering in nginx, and creates a migration script for 0.2.11 -> 0.2.12.
Fixes https://github.com/Start9Labs/embassy-os/issues/271
> disable buffering in nginx

- ui/src/app/app-config/config-cursor.ts
Fixes the issue where an old config with a new config spec sometimes renders the config inaccessible, with the error `n is undefined`
> Fix "n is undefined" config spec change bug

- appmgr/src/error.rs
- appmgr/src/lib.rs
- appmgr/src/logs.rs
- appmgr/src/system.rs
- appmgr/src/util/mod.rs
This PR implements the `package.logs` endpoint, and refactors the `system.logs` endpoint to use this new interface.
The call takes an `id`, a `limit`, a [journald-style] `cursor`, and a `before_flag`, and returns a `LogResponse`, which is an array of `LogEntry`s (themselves a `timestamp` and a `message`), a `start_cursor`, and an `end_cursor`.
> package logs rpc endpoint

- appmgr/Cargo.lock
- appmgr/Cargo.toml
- appmgr/src/bin/embassyd.rs
- appmgr/src/context/rpc.rs
- appmgr/src/util/logger.rs
1. Accepts many `log-module` arguments
2. Creates a trie where the modules and their log filter levels are stored
3. modules that end in `*` will include all submodules when logging
> implements module level logging

- appmgr/src/config/mod.rs
- appmgr/src/config/spec.rs
- appmgr/src/db/model.rs
- appmgr/src/s9pk/manifest.rs
- appmgr/src/volume.rs
This PR:
1. Changes pointer enumeration to a Set instead of a Vec
2. Collapses the PackagePointerSpec to a single enum, moving the package_id to a row on each arm
3. Gives the constituent arms a single argument constructor over a unique pointer type
4. Adds a TorKey pointer type
5. Adds permission checking to dereference logic for the TorKey
6. Threads new requirements through the deref logic
It does not refactor the means of config dereference traversal. It also doesn't remove the `validate` call from the ValueSpec trait.
> Tor Key Pointers

- setup-wizard/src/app/pages/embassy/embassy.page.html
- setup-wizard/src/app/services/api/mock-api.service.ts
Disable selecting an embassy drive in the wizard if less than 32 gb
> drive capacity disable

- appmgr/src/db/model.rs
- appmgr/src/install/mod.rs
No ticket.
This is to address an instance of non-canonical lock ordering. We realized that this value, while written to, is never read and therefore not needed.
> removed broken packages entry in patchdb

- appmgr/src/net/mod.rs
- appmgr/src/net/nginx.rs
- appmgr/src/net/ssl.rs
This feature was originally intended for LND, because I thought LND allowed externally-generated SSL certs. Apparently it doesn't. But this feature might still be useful.
> add .embassy domains to system-generated ssl certs

- appmgr/src/net/nginx.conf.template
Discovered as a result of visiting btcpay on .local over https:
`BTCPay is expecting you to access this website from http://<REDACTED>.local/. If you use a reverse proxy, please set the X-Forwarded-Proto header to https`
> add protocol header for proxied services

- appmgr/src/config/spec.rs
relevant: https://github.com/Start9Labs/cups-messenger/issues/13
> return null for tor-key pointer if doesn't exist

- build/write-image.sh
NO TICKET
fixes a bug where system images would never be loaded without system rebuild
> build docker state on first startup

- backend/src/sound.rs
- backend/src/update/mod.rs
- build/rip-image.sh
alright, this is a weird pr. There's a few things going on here:
1. There is a race condition with exporting the sound interface if it has recently been unexported. we fix this by waiting on the period file to exist before continuing.
2. If an update fails partway, we cannot safely address it using `/dev/disk/by-label`. We address this by hardcoding a relationship between labels and their logicalnames. This may require a more elegant solution when porting to other hardware platforms.
3. If an update fails partway, the downloaded, but corrupt filesystem still holds its label. We fix this by using a label for updates that is neither `green` nor `blue`.
4. There is a lock escalation error with the unstable flag. We fix this by locking server-info at the beginning of the update flow.
> fix issues with failed updates

- README.md
Updates README screenshots to look like:
> fix arrangement and sizing of screenshots

- backend/src/net/mdns.rs
This is in service of #1036. This doesn't fix it but should improve insight as to what is happening. Upon digging deeper into the avahi docs it seems that it is possible to get into collision states from which we must repair and it is also possible for avahi-daemon's misbehavior to have adverse impact to embassyd's ability to support .local. These changes should tell us what kind of error states we are hitting. We should merge this so that Chris can continue his testing that produces this bug, from there we can scrape the logs and learn what is going on and address it.
> adds some investigative logging and improves error handling for mdns

- backend/src/init.rs
- build/write-image.sh
NO TICKET
if the docker state does not exist, we need to build it. we hacked around this by adding the `system-rebuild` file to fresh builds, but this doesn't help if you set up a fresh drive with a previously used card.
> perform docker state build if folder doesn't exist

- backend/src/update/mod.rs
- build/initialization.sh
This PR is in response to #1164 but unintuitively.
The actual problem originally arose from having different machine ids every boot. This was due to running cloud init every boot back in the couple of weeks where we were on 21.10.
RaspiOS implicitly fixed that by doing away with cloud-init. However, the reason we had cloud-init in the first place is to make ssh host keys different per machine.
This PR ultimately ensures that every Embassy has a unique machine-id and set of ssh keys, and that those materials are preserved across OTA updates.
> Make machine-ids and ssh host keys unique

- backend/src/backup/backup_bulk.rs
This should fix a bug where the *second* app being backed up would sometimes deadlock.
> fix lock scope

- build/initialization.sh
- build/write-image.sh
this is one of the weirder things I've had to debug. Thanks to @k0gen for calling attention to it.
Before this, calling `disk.list` would disable the overlay on next reboot. wild.
> fix overlay disabling when looking at disk drives

- backend/src/bin/embassyd.rs
- backend/src/context/rpc.rs
- backend/src/setup.rs
this was preventing full embassy restores from completing
> fix bug that prevents rpc context from dropping without server shutdown

- frontend/projects/ui/src/app/pages/notifications/notifications.page.html
- frontend/projects/ui/src/app/pages/notifications/notifications.page.ts
NO TICKET
if the pkg exists in package-data, use the title on the manifest when displaying notes, otherwise show the pkg id
> Show pkg title in notes if manifest exists

- backend/src/sound.rs
Speed up shutdown sound from 120 to 200 qpm to make it sound more crisp
> speed up shutdown

- build/initialization.sh
this prevents us from shipping everyone the same tor state, and means restarts will result in a tor state rebuild, which can help resolve connectivity issues
> start with clean tor state

- backend/src/context/rpc.rs
- backend/src/context/setup.rs
we were parsing a .yaml file as toml in some circumstances
> use consistent config file type

- backend/embassy-init.service
- backend/src/init.rs
- build/initialization.sh
this fixes our time sync, and uses systemd-timesyncd.service instead of ntp
> wait for time sync up to 60s

- frontend/package.json
Need this so I as a Dev can touch my Dev box (that I ssh into) and port-forward to my thin client and see the web page hosted there.
> fix: Be able to port forward and see frontend

- Makefile
If for some reason `make` will be interrupted, wget will try to download `.zip` file and cause the name is taken it will save it to `.zip.1` which wont be recognized. This fixes it + you save some internet bandwidth by continuing the download.
> ⬐ smarter wget

- backend/embassyd.service
- build/docker-engine.slice
- build/initialization.sh
> prevent the kernel from OOMKilling embassyd

- backend/embassyd.service
- build/docker-engine.slice
- build/initialization.sh
Videos showing a removal and install of service
https://user-images.githubusercontent.com/2364004/164785705-210c1bb3-8bfb-4a4b-b112-e3e162ffdcb9.mp4
https://user-images.githubusercontent.com/2364004/164785712-43b14e47-c4c1-4b97-8e28-7239a7c6e857.mp4
https://user-images.githubusercontent.com/2364004/164756599-24730c8f-14ef-41f2-85aa-dbd079bc2948.mp4
Snap of the system logs
Snap of an app logs
Snap of version
> Feat  new locking

- backend/src/net/nginx.conf.template
- backend/src/net/nginx.rs
The problem
My app (https://github.com/squeaknode/squeaknode-wrapper) uses Flask for the UI interface. The Flask server uses redirects for the login/logout/index routes. When a redirect happens in the Squeaknode app, it tries to redirect to "http://..." because Flask does not know that it is behind a reverse proxy.
The solution
Add a config to Nginx so that all redirects go to the correct "https://..." url.
I tested this by manually editing the `/etc/nginx/sites-enabled/squeaknode_main_443.conf` file to include:
```
proxy_redirect http://$host/ https://$host/;
```
Then I did `systemctl reload nginx`.
After that, the Squeaknode login/logout works fine.
> Add nginx config for proxy redirect

- frontend/.gitignore
- frontend/README.md
- frontend/config-sample.json
- frontend/package.json
- frontend/proxy.conf.json.sample
Make use of angular proxy configuration to use a local/development front end to test with live data on an Embassy (remote backend).
> Proxy local frontend to remote backend

- backend/src/config/mod.rs
- backend/src/db/model.rs
- backend/src/dependencies.rs
- backend/src/install/cleanup.rs
- backend/src/install/mod.rs
- backend/src/manager/health.rs
- backend/src/procedure/mod.rs
Currently can't do auto configure because the system was broken during the refactor of Bulk Locks. Now the solution is to make sure that I couldn't swap dependencies with dependents with a new type.
> fix: Dependency vs dependents

- backend/src/config/spec.rs
- backend/test/config-spec/lnd-invalid-regex.yaml
- backend/test/config-spec/lnd-missing-pattern-description.yaml
- backend/test/config-spec/lnd-missing-pattern.yaml
> fixes regex black hole

- backend/Cargo.lock
- backend/Cargo.toml
- backend/install-sdk.sh
- backend/src/backup/target/mod.rs
- backend/src/context/cli.rs
- backend/src/context/diagnostic.rs
- backend/src/context/rpc.rs
- backend/src/context/sdk.rs
- backend/src/context/setup.rs
- backend/src/developer/mod.rs
- backend/src/disk/mount/filesystem/block_dev.rs
- backend/src/disk/mount/filesystem/cifs.rs
- backend/src/disk/mount/filesystem/ecryptfs.rs
- backend/src/disk/mount/filesystem/label.rs
- backend/src/disk/mount/filesystem/mod.rs
- backend/src/error.rs
- backend/src/lib.rs
- backend/src/s9pk/builder.rs
- backend/src/s9pk/reader.rs
- backend/src/setup.rs
- backend/src/util/config.rs
- backend/src/util/mod.rs
> allow embassy-cli not as root

- backend/Cargo.lock
- backend/Cargo.toml
- backend/src/procedure/docker.rs
We are trying to solve that we where seeing a memory leak where certain packages where filling the memory over time.
Right now because we are reading the lines in the read buffer there could be a possibility that the lines are gigantic, and would eat up memory
> fix: potential fix for the docker leaking the errors and such

- backend/src/config/action.rs
- backend/src/context/cli.rs
- system-images/compat/Cargo.lock
> fix "missing proxy" error in embassy-cli

- libs/artifacts/types.d.ts
Add the types for the union and enum
Rust looked like 
And the d.ts looks like
> chore: Update the lite types to include the union and enum

- backend/src/procedure/mod.rs
While debuging why configSet was slow, was using this trace. @chrisguida  thought it would be nice if others could trace this too.
> chore: Add tracing for debuging the js procedure slowness

- Makefile
This is happening when we only want to build a sdk + cli.
The issue arises that there are dependencies now that are needed in the sdk that are not controlled.
We use the makefile to do our flows.
Therefore we see the solution is to use the make file flow `make clean; make sdk` to ensure it matches our other flows.
> feat: Make sdk

- backend/src/backup/restore.rs
Fixes https://github.com/Start9Labs/embassy-os/issues/1488
First, we see what it was like before hand to recreate.
https://user-images.githubusercontent.com/2364004/175098471-667254d9-e824-4e7f-b6fd-e66a1adfe645.mp4
Then after the fix we run.
https://user-images.githubusercontent.com/2364004/175098519-a7182629-8484-4520-b2f9-71f5d204a6ea.mp4
Thus we see that we have fixed the issue. 
Note: The password used was for the old backup
> fix: Make it so we only need the password on the backup

- frontend/projects/ui/src/app/util/properties.util.ts
During the current js version of the proxy, getting an error in the properties because it is failing to check the shape
Looks like the issue was that the value was coming back but as null, and I wasn't dealing with the null case, just the undefined case.
Picture of the properties on the proxy working now
> fix: Properties had a null description

- build/initialization.sh
As of apt 1.5, the package apt-transport-https is no longer required because https:// is supported out of the box.
Reference: https://packages.debian.org/bullseye/apt-transport-https "This is a dummy transitional package - https support has been moved into the apt package in 1.5. It can be safely removed."  Apt is currently at 2.2.4.
Use a sed one-liner to convert all repos in /etc/apt/sources.list and /etc/apt/sources.list.d/*.list that are http:// to https:// (https:// is available for all http:// URLs currently referenced in EmbassyOS's apt repos).
> Default to https:// urls for repositories, remove apt-transport-https

- backend/src/procedure/docker.rs
Fixes: https://github.com/Start9Labs/embassy-os/issues/557
Proof:
> sdk: don't allow mounts in inject actions

- backend/src/net/ssl.rs
> trust local ca

- backend/Cargo.lock
- backend/src/backup/backup_bulk.rs
- backend/src/backup/mod.rs
- backend/src/context/rpc.rs
- backend/src/disk/mount/backup.rs
- backend/src/disk/quirks.rs
- backend/src/util/mod.rs
- libs/Cargo.lock
- libs/helpers/Cargo.toml
- libs/helpers/src/lib.rs
- libs/js_engine/Cargo.toml
- libs/js_engine/src/lib.rs
Renames are safer and are more atomic than just writing to a file. 
Why not just using a `tmp` file:
- What if the service is writing it's own `.tmp` files and the file names conflict? we could clobber them and cause weird bugs in the service
- What if the service has behaviors that depend on stat-ing a directory? The new file could cause it to try to do something invalid
Nothing needs to change on the api side. Thus the old tests still working is proof that it works
> feat: atomic writing

- backend/src/update/mod.rs
- libs/Cargo.lock
this means we can stop publishing os versions to fake version numbers to allow continuous updates.
> allow server.update to update to current version

- backend/src/install/mod.rs
for some reason the base url now has a trailing slash, so calls to it that add a leading slash will end up calling `//rest/rpc`, with two slashes. i have no idea why this has changed, but this will fix cli installs.
> fix cli install

- .github/workflows/README.md
- .github/workflows/backend-pr.yaml
- .github/workflows/backend.yaml
- .github/workflows/frontend.yaml
- .github/workflows/product.yaml
Here is some more pipeline work for your consideration. This adds a x86_64 build for the backend, in addition to the existing aarch64 build. Also added running the backend unittests on both platforms.
Relates to #1032 and #981
The changes made are:
* Build the backend for x86_64
* Use the target names x86_64 and aarch64 (instead of amd64 and arm64) consistently in the pipeline
* Use the same rust version everywhere
* Remove some unnecessary build steps, or add an `if` when platform specific
The current Makefile only targets aarch64, so for the build and test commands I've had to ignore the Makefile.
To run the unittests I found that some tests expect eOS environment features, such as existing files or directories. Perhaps they should be classified as integration tests and run in the eOS …
> add x86 build and run unittests to backend pipeline

- .github/workflows/backend.yaml
- .github/workflows/frontend.yaml
- .github/workflows/product.yaml
As a follow-up on #1682 this adds a more sensible timeout on the pipelines jobs (the default apparently was 6 hours) and adds the ca-certificates apt package to the test container.
> Set pipeline job timeouts and add ca-certificates to test container

- build/initialization.sh
This should fix a long standing issue where the Bluetooth service was starting up at boot.
closes #862
> Disable bluetooth properly #862

- backend/Cargo.toml
- backend/src/util/http_reader.rs
this modifies HttpReader to automatically resume downloads if the connection closes before the message completes. It also reduces the memory footprint of HttpReader by writing chunks directly to the buffer, instead of allocating one.
> [feat]: resumable downloads

- build/initialization.sh
I also removed the src line because we won't use the tor source repository anytime soon if ever.
> 🧅 replace instead of adding tor repository

- .github/workflows/backend.yaml
- backend/README.md
- backend/src/sound.rs
- build/lib/proxy.pac
- build/lib/scripts/chroot-and-upgrade
- build/lib/scripts/enable-kiosk
- build/lib/scripts/firefox-trust-cert
- build/raspberry-pi/initialization.sh
H/T to @k0gen for the kiosk mode
> build improvements

- .github/workflows/backend.yaml
- .github/workflows/frontend.yaml
- .github/workflows/reusable-workflow.yaml
This PR fixes the current errors and warnings in the build pipeline. The changes are:
* Update the version of some actions to fix the recent warnings (see https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ and https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)
* Run apt-get update before apt-get install in the backend pipeline to fix a build error
* Replace actions-rs/toolchain with a bash script because it's throwing a warning and hasn't been updated in a while
> Update build pipeline

- backend/src/init.rs
- backend/src/install/cleanup.rs
- backend/src/install/mod.rs
- backend/src/setup.rs
- backend/src/update/mod.rs
- libs/helpers/src/lib.rs
- libs/helpers/src/rsync.rs
This way, migrating a data drive to a new arch will seamlessly switch to using containers from the target arch.
> fix migration to support portable fatties

- backend/src/version/v0_3_3.rs
This is to fix a bug in the UI
> fix: Ensure that during migration we make the urls have a trailing slash

- backend/src/manager/mod.rs
We start with a running searxng.
Then we go and upgrade this service. 
Issue: During the installation process we see it get stuck in the installation state.
The synchronizer is converting the service from killed -> sleep.
Also there is a state machine hell in this service.
Video showing that the `about - bad flow` is no longer recreatable.
Note: This still takes a long time since we are waiting for a timeout in the process of the searxng.
https://user-images.githubusercontent.com/2364004/211415883-675994cb-df72-4c97-a40a-89a63de8e158.mp4
> fix: Manager's exit not stopping

- backend/src/bin/embassyd.rs
- backend/src/net/tor.rs
> remove tor health daemon

- backend/src/diagnostic.rs
- frontend/projects/diagnostic-ui/src/app/pages/home/home.page.html
- frontend/projects/diagnostic-ui/src/app/pages/home/home.page.ts
- frontend/projects/diagnostic-ui/src/app/services/api/api.service.ts
- frontend/projects/diagnostic-ui/src/app/services/api/live-api.service.ts
- frontend/projects/diagnostic-ui/src/app/services/api/mock-api.service.ts
- frontend/projects/shared/styles/shared.scss
- frontend/projects/ui/src/app/pages/server-routes/server-show/server-show.page.ts
- frontend/projects/ui/src/styles.scss
Closes #1898
closes #1987
Awaitng BE endpoint for `diagnostic.rebuild`.
`diagnostic.disk.repair` already exists.
> Add system rebuild and disk repair to Diagnostic UI

- build/raspberry-pi/make-image.sh
fdisk lives in /usr/sbin/fdisk so it's not available to or in the $PATH of unprivileged users.
Without sudo, unless you build as root, you receive this error:
```
$ make embassyos-raspi.img ARCH=aarch64
...
make[1]: Leaving directory '/home/user/Dev/embassy-os/system-images/binfmt'
! test -f embassyos-raspi.img || rm embassyos-raspi.img
./build/raspberry-pi/make-image.sh
./build/raspberry-pi/make-image.sh: line 27: fdisk: command not found
make: *** [Makefile:67: embassyos-raspi.img] Error 127
make: *** Deleting file 'embassyos-raspi.img'
```
With the `sudo fidsk` in this fix, my make completed successfully as a regular user.
> Always invoke fdisk with `sudo fdisk` in build/raspberry-pi/make-image.sh

- backend/src/procedure/js_scripts.rs
- backend/test/js_action_execute/package-data/scripts/test-package/0.3.0.3/embassy.js
- libs/js_engine/src/lib.rs
Fixes : #2121 
Recreated the broken situation in the test.
Then fixed, it was that we where checking the parent. Makes sense that was wrong
> fix: Zero op new dir dies.

- frontend/projects/shared/src/util/misc.util.ts
- frontend/projects/ui/src/app/app/menu/menu.component.ts
- frontend/projects/ui/src/app/pages/marketplace-routes/marketplace-list/marketplace-list.page.ts
- frontend/projects/ui/src/app/pages/updates/updates.page.html
- frontend/projects/ui/src/app/pages/updates/updates.page.ts
- frontend/projects/ui/src/app/services/api/mock-patch.ts
- frontend/projects/ui/src/app/services/marketplace.service.ts
**Goals**
1. Registries containing the string 'alpha' or 'beta' should only show in the Updates Tab and count towards updates badge count if dev tools enabled.
2. In the Updates Tab, service updates should show in _every_ registry where there is an update available (not just the registry from which it was originally installed)
3. Updates badge count should be de-duplicated. For example, if there is an update available for Bitcoin in 3 different registries, the badge should only count that as 1.
> Better Updates Tab and updates count

- frontend/README.md
- frontend/projects/diagnostic-ui/src/styles.scss
- frontend/projects/install-wizard/src/app/pages/home/home.page.scss
- frontend/projects/install-wizard/src/styles.scss
- frontend/projects/setup-wizard/src/app/pages/success/download-doc/download-doc.component.html
- frontend/projects/setup-wizard/src/styles.scss
- frontend/projects/ui/src/app/components/widget-card/widget-card.component.scss
- frontend/projects/ui/src/styles.scss
While the fonts are loading, headings default to a serif font, so it looks a bit funny and it's more jarring when the sans-serif fonts load.
Some places already had a fallback (e.g. the [side navigation](https://github.com/Start9Labs/embassy-os/blob/master/frontend/projects/shared/styles/shared.scss#L114)), this PR just adds it everywhere else.
- https://css-tricks.com/css-basics-fallback-font-stacks-robust-web-typography/
> Add sans-serif font fallback

- build/lib/depends
This may help anybody running StartOS in a VM to:
* properly shutdown the guest, instead of relying on ACPI commands
* freeze the guest file system when making a backup/snapshot, entering suspend, and thawing filesystems
* In the phase when the guest (VM) is resumed after pause (for example after shapshot) it immediately synchronizes its time with the hypervisor using qemu-guest-agent (as first step).
More info:
https://wiki.libvirt.org/Qemu_guest_agent.html
https://pve.proxmox.com/wiki/Qemu-guest-agent
> Add qemu-guest-agent for advanced VM shutdown options

- check-version.sh
We found that we couldn't compile this on the mac arm os
> fix: Make check-version posix compliant

- frontend/projects/ui/src/app/pages/login/login.page.html
* The password set dialogue forces maxlenght=64 but when logging in, the dialogue does not forces this. This makes an issue when the user copy/pastes a longer than 64 character password in boxes. closes #2375
> frontend: ui: bugfix: consistent password length.

- backend/src/developer/mod.rs
* `start-sdk init` used to run completely silent. Now we are showing the current/generated developer.key.pem based on ticket https://github.com/Start9Labs/start-os/issues/1854
sample run:
```
➜  backend git:(sdk_init_message-fixes1854) ✗ start-sdk init
New developer key generated at /Users/jadi/.embassy/developer.key.pem
➜  backend git:(sdk_init_message-fixes1854) ✗ start-sdk init
Developer key already exists at /Users/jadi/.embassy/developer.key.pem
```
> backend: sdk init: output file location. fixes #1854

- backend/src/db/model.rs
- backend/src/diagnostic.rs
- backend/src/logs.rs
- backend/src/net/tor.rs
- backend/src/system.rs
Os logs now
Mempool logs now
Now the logs of mempool are not going into the Os Logs now, which is what it used to do
> fix: Add in logging for the podman in the system logs

- frontend/projects/setup-wizard/src/app/modals/password/password.page.html
- frontend/projects/ui/src/app/pages/login/login.page.html
Removes html maxLength. Instead rely on JS validation for clarity.
> closes #2454

- backend/src/bins/start_deno.rs
That during the testing there was found a noise in the logs that seemed to indicate error
The actual solution was to change all the sdk that all the services use to no longer say error in the info. 
But the end case is that we are just going to filter up to the warn, and remove the noise in the logs for the services and js.
https://github.com/Start9Labs/start-os/assets/2364004/18525b35-bdb4-42cf-8dca-c47ddc22db4a
> fix: Logging in deno to filter out the info

- frontend/projects/setup-wizard/src/app/pages/success/success.page.ts
- frontend/projects/ui/src/app/app/menu/menu.component.html
- frontend/projects/ui/src/app/app/menu/menu.component.ts
- frontend/projects/ui/src/app/components/widget-card/widget-card.component.scss
- frontend/projects/ui/src/app/components/widget-list/widget-list.component.html
- frontend/projects/ui/src/app/components/widget-list/widget-list.component.scss
- frontend/projects/ui/src/app/components/widget-list/widget-list.component.ts
- frontend/projects/ui/src/app/pages/login/ca-wizard/ca-wizard.component.html
- frontend/projects/ui/src/app/pages/login/ca-wizard/ca-wizard.component.scss
- frontend/projects/ui/src/app/pages/login/ca-wizard/ca-wizard.component.ts
> rework ca-wiz and add icons to menu for warnings

- core/startos/src/context/rpc.rs
- core/startos/src/init.rs
the previous implementation launched the ntp status check daemon during `start-init`. since `start-init` uses a different tokio runtime than `startd`, this daemon is shutdown after initialization completes. I have moved the ntp status check daemon to `RpcContext::init`.
> fix ntp sync status check daemon

- core/install-sdk.sh
- core/startos/src/manager/manager_seed.rs
- core/startos/src/util/docker.rs
So the timeout that was included in the original is not working therefore we move to a doubling with a timeout
> fix: Docker stopping will include a timeout

- container-runtime/src/Adapters/RpcListener.ts
- container-runtime/src/Adapters/Systems/SystemForEmbassy/index.ts
- container-runtime/src/Adapters/Systems/SystemForStartOs.ts
- container-runtime/src/Interfaces/System.ts
- core/Cargo.lock
- sdk/lib/types.ts
I want to make all the routes for each of the service adapters for the embassy and start9 services use fn's instead of routes
> chore: reimplement refactor for the changes

- sdk/lib/StartSdk.ts
- sdk/lib/types.ts
Currently the start sdk that we expose calls some of the effects. And there are others that need to be called via the effects object. The idea is that all the effects that could and should be called are from the startsdk side
> feat: Adding in the effects to the startSdk

- container-runtime/src/Adapters/Systems/SystemForEmbassy/DockerProcedureContainer.ts
- sdk/package/lib/mainFn/CommandController.ts
- sdk/package/lib/mainFn/Daemon.ts
- sdk/package/lib/mainFn/Daemons.ts
- sdk/package/lib/util/SubContainer.ts
The default 'stdio' option of a node ChildProcess is 'pipe', causing no logs to be captured from service daemons.
Added an option 'stdio', defaulting to 'inherit' (this pipes stdio to the parent process, causing the logs to appear again).
If onStdout/onStderr hooks are used, then we switch to 'pipe' and it is the responsibility of whoever uses those to deal with logging.
> sdk: fix piping stdio of Daemons, support onStdOut/onStderr

- sdk/package/lib/util/SubContainer.ts
We've seen "subcontainer failed to launch" but additional information was unavailable because the launch command is muted. This unmutes the command
> do not mute logs of subcontainer launch dummy

- build/lib/scripts/chroot-and-upgrade
By binding the rootfs into the chroot, grub-probe can successfully run inside the chroot
> allow updating grub from chroot-and-upgrade

- sdk/base/lib/actions/input/builder/value.ts
- sdk/base/lib/test/startosTypeValidation.test.ts
> remove file from input spec

- debian/postinst
Enable full system visibility for headless StartOS servers through serial port connection. Administrators can now monitor boot process, kernel messages, and access system console without requiring a display.
> Add serial console support for headless operation

- build/lib/scripts/gather_debug_info.sh
- debian/postinst
This PR introduces a new script `gather_debug_info.sh` to collect comprehensive system debug information for StartOS.
> Add System Debug Information Gathering Script

- debian/postinst
Fixing this: 
to look like this:
> Escape backslashes in /etc/issue to prevent unwanted newlines

- .github/workflows/startos-iso.yaml
- .github/workflows/test.yaml
i noticed in a previous PR #2850 that the github workflows were failing due to one of the workflows using a deprecated version. so i went ahead and just updated the ones that were out of date.
> update github workflow actions to most recent versions

- debian/postinst
Changing fallback DNS from Google's 8.8.8.8 to Cloudflare's 1.1.1.1:
* Cloudflare's DNS is mirrored and anycast from ~330 localities globally vs Google's ~200
* Cloudflare's DNS does not transmit the [EDNS Client Subnet](https://en.wikipedia.org/wiki/EDNS_Client_Subnet) while Google does.  EDNS is a DNS extension that forwards the anonymized (removal the last octet for ipv4) client's IP address to all DNS servers in the recursive resolution chain -- including the server that controls the target name, so that CDN systems can give out the best-performing answer based on a geoip database.  While that's good for maximum performance, it's bad for privacy.  With this fallback DNS option, presumably we just want something that works while retaining more privacy.  The IP address from which …
> Fallback DNS/NTP server privacy enhancements

- build/lib/motd
This PR overhauls the StartOS MOTD banner to deliver a visually appealing, informative, and robust login experience for all users and environments (SSH, local, serial, etc.). All color and formatting is POSIX-compliant and MOTD-safe, with full fallback handling.
Fully POSIX, Quick, No External Dependencies. Script runs as `/bin/sh`, works even if environment is minimal.
All dependencies (`start-cli`,` jq`, `free`, `df`, `awk` and `sed`) are already included in StartOS.
Feel free to suggest more environment coloring or order tweaks!
> Motd Redesign - Visual and Structural Upgrade

- core/startos/src/developer/mod.rs
- core/startos/src/middleware/auth.rs
Was this a typo? Perhaps `0o640` was the intention, which would allow the owner to read/write and the group to read. For a private key, the most secure standard is `0o600` to restrict all access to the owner.
> Fix file permissions for developer key and auth cookie
