- agent/config/routes
- agent/src/Application.hs
- agent/src/Foundation.hs
- agent/src/Handler/Apps.hs
- agent/src/Handler/Types/Apps.hs
- agent/src/Lib/Algebra/Domain/AppMgr.hs
- agent/src/Lib/Types/NetAddress.hs
This includes the agent changes required for lan enable and disable, this will not work until the appmgr changes are included.
> finishes lan support for the agent

- README.md
Added community matrix and mastodon shields
> 🌠 Image display fix

- ui/src/app/components/config-header/config-header.component.html
- ui/src/app/services/api/mock-api.service.ts
Fixes https://github.com/Start9Labs/embassy-os/issues/51
> enable markdown in config property descriptions and warnings

- appmgr/src/lib.rs
- appmgr/src/properties.rs
- appmgr/src/s9pk/manifest.rs
- compat/Cargo.lock
This feature implements the package properties rpc endpoint.
> package properties rpc endpoint

- appmgr/src/bin/embassy-init.rs
- appmgr/src/install/mod.rs
> fix rpc context argument for embassy init

- build/README.md
Further detail added to buildguide based on testing.  Probably will need some more refinement, but getting close
> Build README update

- appmgr/src/context/rpc.rs
- appmgr/src/db/mod.rs
- appmgr/src/middleware/auth.rs
> Close websocket on session kill

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/os-feature-request.md
Adds bug report and feature request templates for Issues to EOS
> Update issue templates

- ui/src/app/components/status/status.component.html
https://github.com/Start9Labs/embassy-os/issues/811
> install messaging

- ui/src/app/pages/server-routes/wifi/wifi.page.ts
Delete wifi from ui if connection fails
> remove wifi on failure

- appmgr/src/context/rpc.rs
- appmgr/src/db/model.rs
- appmgr/src/error.rs
- appmgr/src/install/cleanup.rs
- appmgr/src/install/mod.rs
- appmgr/src/manager/mod.rs
> clean up transient state on boot

- setup-wizard/src/app/pages/recover/recover.page.html
- setup-wizard/src/app/services/api/live-api.service.ts
https://github.com/orgs/Start9Labs/projects/38?card_filter_query=assignee%3Adrewans
> recovery drive failing

- setup-wizard/src/app/pages/success/success.page.html
- setup-wizard/src/app/pages/success/success.page.ts
https://github.com/Start9Labs/embassy-os/issues/809
Use saved base 64 cert instead of path to file
> download cert from base 64

- ui/src/app/components/logs/logs.page.html
- ui/src/app/components/logs/logs.page.ts
https://github.com/Start9Labs/embassy-os/issues/826
> logs monospace no new line in between

- ui/src/app/pages/apps-routes/app-list/app-list.page.ts
https://github.com/Start9Labs/embassy-os/issues/835
> empty list issue

- ui/src/app/services/api/embassy-mock-api.service.ts
- ui/src/app/services/patch-db/data-model.ts
- ui/src/app/services/pkg-status-rendering.service.ts
https://github.com/Start9Labs/embassy-os/issues/810
> starting status

- appmgr/src/status/health_check.rs
- appmgr/src/status/mod.rs
Closes embassyd portion of #817 
Closes embassyd portion of #848
> adds name, description; changes critical boolean to severity enum

- appmgr/src/status/health_check.rs
> adds defaults to healthcheck severity

- ui/src/app/pages/apps-routes/app-show/app-show.module.ts
- ui/src/app/pages/apps-routes/app-show/app-show.page.html
- ui/src/app/pages/apps-routes/app-show/app-show.page.ts
- ui/src/app/services/patch-db/data-model.ts
https://github.com/Start9Labs/embassy-os/issues/817
> health check name and description

- ui/src/app/components/form-object/form-object.component.html
- ui/src/app/components/form-object/form-object.component.ts
- ui/src/app/services/api/api.fixures.ts
https://github.com/Start9Labs/embassy-os/issues/859
> union tag description

- build/write-image.sh
> blacklist uas kernel module

- setup-wizard/src/app/pages/embassy/embassy.page.html
- ui/src/app/components/logs/logs.page.scss
- ui/src/app/components/status/status.component.html
- ui/src/app/components/status/status.component.scss
- ui/src/app/components/status/status.component.ts
- ui/src/app/pages/apps-routes/app-list/app-list-icon/app-list-icon.component.scss
- ui/src/app/pages/apps-routes/app-list/app-list-icon/app-list-icon.component.ts
- ui/src/app/pages/apps-routes/app-list/app-list-pkg/app-list-pkg.component.html
- ui/src/app/pages/apps-routes/app-list/app-list-reorder/app-list-reorder.component.html
- ui/src/app/pages/marketplace-routes/marketplace-list/marketplace-list.page.html
- ui/src/app/pages/marketplace-routes/marketplace-show/marketplace-show.page.html
- ui/src/app/pages/server-routes/wifi/wifi.page.ts
- ui/src/app/pipes/install-state.pipe.ts
- ui/src/app/services/api/api.fixures.ts
- ui/src/app/services/api/embassy-mock-api.service.ts
- ui/src/app/util/package-loading-progress.ts
- ui/src/global.scss
https://github.com/Start9Labs/embassy-os/issues/877
Also, replace ion spinner with "..."
Fix icon issue in app list page.
Fix NaN issue with mocks and change display in installProgress pipe
> dots compromise

- setup-wizard/src/app/pages/success/success.page.html
- setup-wizard/src/app/services/api/live-api.service.ts
- ui/src/app/pages/marketplace-routes/marketplace.service.ts
- ui/src/app/pages/server-routes/restore/restore.component.ts
- ui/src/app/pages/server-routes/server-backup/server-backup.page.ts
- ui/src/app/services/api/api.types.ts
- ui/src/app/services/api/embassy-live-api.service.ts
- ui/src/app/services/api/embassy-mock-api.service.ts
> Rebased backup path

- ui/src/app/pages/apps-routes/app-list/app-list-empty/app-list-empty.component.html
https://github.com/Start9Labs/embassy-os/issues/902
> marketplace link fix

- ui/src/app/components/logs/logs.page.ts
Error on init when loading logs page.
> logs page init err

- build/initialization.sh
- build/write-image.sh
> disable login as `ubuntu`

- appmgr/src/action/docker.rs
> delete container before action

- appmgr/src/nginx/diagnostic-ui.conf
- appmgr/src/nginx/main-ui.conf.template
- appmgr/src/nginx/setup-wizard.conf
> enable gzip compression

- appmgr/src/config/mod.rs
- appmgr/src/dependencies.rs
- appmgr/src/install/cleanup.rs
- appmgr/src/install/mod.rs
- appmgr/src/install/update.rs
> correctly handle self as current dependent

- ui/src/app/pages/apps-routes/app-list/app-list-empty/app-list-empty.component.html
- ui/src/app/pages/notifications/notifications.page.html
- ui/src/app/pages/notifications/notifications.page.scss
- ui/src/app/pages/notifications/notifications.page.ts
- ui/src/global.scss
https://github.com/Start9Labs/embassy-os/issues/888
> View full message

- appmgr/src/backup/target/cifs.rs
- appmgr/src/disk/mount/filesystem/cifs.rs
- appmgr/src/net/mdns.rs
- build/initialization.sh
- setup-wizard/src/app/modals/cifs-modal/cifs-modal.page.html
- setup-wizard/src/app/modals/cifs-modal/cifs-modal.page.ts
- setup-wizard/src/app/pages/recover/recover.page.html
- ui/src/app/components/backup-drives/backup-drives.component.html
- ui/src/app/components/backup-drives/backup-drives.component.ts
- ui/src/app/components/install-wizard/install-wizard.component.ts
- ui/src/app/components/install-wizard/prebaked-wizards.ts
- ui/src/app/components/status/status.component.html
- ui/src/app/pages/marketplace-routes/marketplace-list/marketplace-list.page.html
- ui/src/app/pages/marketplace-routes/marketplace-show/marketplace-show.page.html
- ui/src/app/pages/server-routes/ssh-keys/ssh-keys.page.ts
- ui/src/app/util/package-loading-progress.ts
- ui/src/global.scss
> allow mdns cifs shares

- ui/src/app/components/status/status.component.html
- ui/src/app/components/status/status.component.module.ts
- ui/src/app/components/status/status.component.ts
- ui/src/app/modules/sharing.module.ts
- ui/src/app/pages/apps-routes/app-list/app-list-pkg/app-list-pkg.component.html
- ui/src/app/pages/apps-routes/app-list/app-list-reorder/app-list-reorder.component.html
- ui/src/app/pages/apps-routes/app-show/app-show.page.html
- ui/src/app/pipes/unit-conversion.pipe.ts
- ui/src/app/services/api/api.fixures.ts
- ui/src/app/services/api/mock-patch.ts
- ui/src/app/services/patch-db/data-model.ts
NO TICKET.
This code uses the sigterm to display message while stopping on the UI.
> sigterm duration and pipe

- ui/src/app/pages/apps-routes/app-show/app-show.page.ts
git push --set-upstream origin view-service-mrktplace
> view service in marketplace

- appmgr/src/bin/embassyd.rs
- appmgr/src/context/rpc.rs
- appmgr/src/lib.rs
- appmgr/src/marketplace.rs
- appmgr/src/nginx/main-ui.conf.template
> add set-marketplace rpc

- appmgr/src/config/mod.rs
- appmgr/src/dependencies.rs
- appmgr/src/install/cleanup.rs
- appmgr/src/install/mod.rs
> rename symbols about dependencies

- appmgr/src/manager/mod.rs
- appmgr/src/net/mod.rs
Fixes: https://github.com/Start9Labs/synapse-wrapper/issues/18
> Fix--startup-sorta-crash

- appmgr/src/bin/embassy-init.rs
- appmgr/src/bin/embassyd.rs
- appmgr/src/shutdown.rs
- appmgr/src/sound.rs
- appmgr/src/update/mod.rs
> change sounds away from mario, replace their use sites

- build/initialization.sh
> upgrade all packages before baking image

- ui/src/app/app.component.ts
- ui/src/app/pages/login/login.page.ts
- ui/src/app/services/api/embassy-api.service.ts
- ui/src/app/services/patch-db/patch-db.service.ts
No Ticket.
Fix polling hanging spinner
> Edits off auto poll

- ui/src/app/components/install-wizard/notes/notes.component.ts
- ui/src/app/pages/marketplace-routes/marketplace-list/marketplace-list.page.html
- ui/src/app/pages/marketplace-routes/marketplace.service.ts
https://github.com/Start9Labs/embassy-os/issues/978
> eos update bugs

- build/initialization.sh
- build/quick-flash.sh
- build/write-image.sh
Magic fixes with Aiden
Making the dd faster for the eos.img
Making the initialization have one less hole
> fix: Build faster

- setup-wizard/src/app/modals/cifs-modal/cifs-modal.page.ts
- setup-wizard/src/app/pages/recover/recover.page.ts
- setup-wizard/src/app/services/api/api.service.ts
this fixes a bug with a type mismatch when recovering during setup. Unsure how this ever worked.
> fix setup recovery

- appmgr/src/hostname.rs
> fix get_hostname

- appmgr/src/manager/mod.rs
> retry failed pause

- appmgr/src/disk/main.rs
> Fix  remove swap

- diagnostic-ui/package-lock.json
- diagnostic-ui/package.json
- diagnostic-ui/src/app/pages/logs/logs.page.ts
https://github.com/Start9Labs/embassy-os/issues/967
> color the logs

- ui/src/app/pages/marketplace-routes/marketplace-show/marketplace-show.page.html
- ui/src/app/pages/marketplace-routes/marketplace-show/marketplace-show.page.ts
https://github.com/Start9Labs/embassy-os/issues/959
> prepend /marketplace

- ui/src/app/pages/apps-routes/app-list/app-list.page.html
- ui/src/app/pages/apps-routes/app-list/app-list.page.ts
- ui/src/app/pages/marketplace-routes/marketplace-list/marketplace-list.page.html
- ui/src/app/pages/marketplace-routes/marketplace-list/marketplace-list.page.ts
- ui/src/app/pages/server-routes/server-show/server-show.page.html
- ui/src/app/services/patch-db/patch-db.service.ts
> login error fix

- ui/src/app/pages/marketplace-routes/marketplace-show/marketplace-show.page.ts
NO ticket
bugfix getting rid of spaces on install
> no spaces in install link

- appmgr/src/disk/main.rs
This PR adds code to return the correct error codes from certain errors when trying to load the main data drive.
In testing this PR, it revealed some weird UX around the `Incorrect Disk` error code. There is a button titled `Use Current Disk`, but clicking it simply calls the forget disk rpc. Then it navigates to a page that implies the embassy has been restarted, but it has not.
@MattDHill @DrewAns please advise.
> add richer error codes to disk import

- setup-wizard/src/app/pages/embassy/embassy.page.html
- ui/src/app/pages/apps-routes/app-show/app-show.page.html
https://github.com/Start9Labs/embassy-os/issues/1028
> load placement bug

- ui/src/app/pages/apps-routes/app-show/components/app-show-health-checks/app-show-health-checks.component.html
- ui/src/app/pages/apps-routes/app-show/pipes/to-health-checks.pipe.ts
https://github.com/Start9Labs/embassy-os/issues/1029
> health spinner fix

- setup-wizard/src/app/app-routing.module.ts
- setup-wizard/src/app/guards/nav-guard.ts
- setup-wizard/src/app/services/api/mock-api.service.ts
NO TICKET
fixes issue with wizard not routing to recovery page
> nav guard bugfix

- diagnostic-ui/src/app/pages/home/home.page.html
- diagnostic-ui/src/app/pages/home/home.page.ts
NO TICKET
request from aiden to restart embassy after forgetting drive
> diagnostic

- setup-wizard/src/app/app-routing.module.ts
- setup-wizard/src/app/services/api/mock-api.service.ts
NO TICKET
quick fix for not initializing setup wizard with routing
> intialize setup wizard with no routing

- Makefile
- appmgr/src/context/rpc.rs
- appmgr/src/db/model.rs
- appmgr/src/init.rs
- appmgr/src/net/wifi.rs
- appmgr/src/nginx/main-ui.conf.template
- build/initialization.sh
- ui/package-lock.json
- ui/src/app/pages/server-routes/wifi/wifi.page.html
- ui/src/app/pages/server-routes/wifi/wifi.page.ts
- ui/src/app/services/api/api.fixures.ts
- ui/src/app/services/api/api.types.ts
Why
---
So we need the ability to have error messages come the frontend, instead of the black hole. NMCli will do this instead of use watching the wpa-suplicant
Also, there are bugs no knowing the nearby wifi's and their respective signal strengths
Backend: 
Frontend:
Test
Thanks
----- 
@DrewAns for the UI work
> feat: Wifi swapped to NMCli

- ui/src/app/components/form-object/form-object.component.html
https://github.com/Start9Labs/embassy-os/issues/1035
> enter click hack

- appmgr/src/backup/target/mod.rs
- appmgr/src/disk/mod.rs
- appmgr/src/disk/quirks.rs
- appmgr/src/disk/util.rs
- appmgr/src/setup.rs
- setup-wizard/src/app/pages/embassy/embassy.page.ts
- setup-wizard/src/app/pages/recover/recover.page.ts
- setup-wizard/src/app/services/api/api.service.ts
- setup-wizard/src/app/services/api/live-api.service.ts
- setup-wizard/src/app/services/api/mock-api.service.ts
we should consider doing this for backup.target.list as well
> reconnect flag

- appmgr/src/action/docker.rs
This ultimately fixes Start9Labs/lnd-wrapper#35
> fixes issue where hostnames would change on package reinstall/update

- ui/src/app/pages/apps-routes/app-show/components/app-show-health-checks/app-show-health-checks.component.html
https://github.com/Start9Labs/embassy-os/issues/1059
> health name off manifest

- setup-wizard/src/app/pages/embassy/embassy.page.html
- setup-wizard/src/app/pages/embassy/embassy.page.ts
- setup-wizard/src/app/services/api/mock-api.service.ts
just addresses refresh button
https://github.com/Start9Labs/embassy/issues/5
> refresh button in embassy drive page in wizard

- ui/src/global.scss
https://github.com/Start9Labs/embassy-os/issues/1081
> highlight text

- system-images/compat/src/main.rs
Fixes https://github.com/Start9Labs/lnd-wrapper/issues/31
> Fix: Show A Message such that the user will know there is something wrong

- appmgr/src/disk/main.rs
> clear dmsetup before import

- setup-wizard/src/app/pages/success/success.page.html
https://github.com/Start9Labs/embassy/issues/5
unplug portion of this ticket
> unplug notification

- build/initialization.sh
- build/user-data
- build/user-data-dev
- build/write-image.sh
NO TICKET
this makes sure cloud-init runs on cloned versions of the image by making sure to reset it after switching to overlay.
> use cloud-init correctly

- appmgr/src/manager/mod.rs
- appmgr/src/manager/sync.rs
> fixes shutdown issues

- appmgr/src/init.rs
- appmgr/src/lib.rs
- appmgr/src/shutdown.rs
prerequisite for #1101 
closes #1087
> only reset docker state on hard-restart

- ui/src/app/pages/server-routes/server-show/server-show.page.ts
- ui/src/app/services/api/api.types.ts
- ui/src/app/services/api/embassy-api.service.ts
- ui/src/app/services/api/embassy-live-api.service.ts
- ui/src/app/services/api/embassy-mock-api.service.ts
https://github.com/Start9Labs/embassy-os/issues/1098
> hard restart feature

- build/00-embassy
- build/write-image.sh
As mentioned in #1083 This is the initial work to get things going ...
> Custom MOTD for EmbassyOS

- backend/src/setup.rs
NO TICKET
The problem solved by this PR is that because bitwarden was renamed to vaultwarden, a naive locking order would result in lock errors when compiling with unstable. We solved this by locking all of the recovered-services data before doing the actual service data migration.
> fixes lock ordering issue in recovery

- ui/src/app/pages/apps-routes/app-list/app-list-rec/app-list-rec.component.ts
https://github.com/Start9Labs/embassy-os/issues/1129
> fix version

- backend/src/db/model.rs
This supports https://github.com/Start9Labs/marketplace-ui/issues/1
> registry.start9.com -> marketplace.start9.com

- backend/src/action/docker.rs
> forcefully remove the container, blowing past 409s

- system-images/compat/src/config/mod.rs
- system-images/compat/src/main.rs
add logic to accept optional dependency list and determine dependencies based on new service configurations
> Properly configure changed optional dependencies 

- build/journald.conf
- build/write-image.sh
> set journald conf file

- frontend/projects/ui/src/app/util/properties.util.ts
Fixes: https://github.com/Start9Labs/filebrowser-wrapper/issues/19
Recreated and proved that it was fixed.
```ts
{
function assertHas(value, property: string) {
if (!(property in value)) {
throw new Error(JSON.stringify({message: "has failure", value, property}))
}
}
const backendResponse = {
"jsonrpc": "2.0",
"result": {
"version": 1,
"data": [
{
"name": "Default Username",
"value": "admin",
"description": "This is your default username. While it is not necessary, you may change it inside your File Browser web application. That change, however, will not be reflected here. If you change your default username and forget your new username, there is no way to regain access.",
"copyable": true,
"qr": false
},
{
"name": "Default Password",
"value": "<redacted>",
"description": "This is your …
```
> fix: Properties

- backend/install-sdk.sh
- backend/src/action/docker.rs
- backend/src/action/mod.rs
- backend/src/backup/mod.rs
- backend/src/config/action.rs
- backend/src/config/mod.rs
- backend/src/developer/mod.rs
- backend/src/id.rs
- backend/src/install/mod.rs
- backend/src/lib.rs
- backend/src/migration.rs
- backend/src/net/interface.rs
- backend/src/s9pk/mod.rs
- backend/src/s9pk/reader.rs
- backend/src/status/health_check.rs
- backend/src/volume.rs
closes #1149 
also validates manifest for internal consistency
> add validation to s9pks

- backend/src/net/interface.rs
- backend/src/net/nginx.rs
> bugfix: inverts mapping for lan config

- frontend/projects/ui/src/app/pages/apps-routes/app-actions/app-actions.page.ts
- frontend/projects/ui/src/app/pages/apps-routes/app-show/components/app-show-status/app-show-status.component.html
- frontend/projects/ui/src/app/pages/apps-routes/app-show/components/app-show-status/app-show-status.component.scss
- frontend/projects/ui/src/app/pages/notifications/notifications.page.html
- frontend/projects/ui/src/app/pages/notifications/notifications.page.scss
https://github.com/Start9Labs/embassy-os/issues/1079
https://github.com/Start9Labs/embassy-os/issues/1128
> ui tickets addressed

- .gitignore
- backend/src/update/mod.rs
- frontend/projects/setup-wizard/src/app/services/api/mock-api.service.ts
- frontend/projects/ui/src/app/app.component.ts
- frontend/projects/ui/src/app/components/install-wizard/prebaked-wizards.ts
- frontend/projects/ui/src/app/modals/app-config/app-config.page.ts
- frontend/projects/ui/src/app/pages/server-routes/server-backup/server-backup.page.ts
- frontend/projects/ui/src/app/pages/server-routes/server-show/server-show.page.html
- frontend/projects/ui/src/app/pages/server-routes/server-show/server-show.page.ts
- frontend/projects/ui/src/app/services/api/api.types.ts
- frontend/projects/ui/src/app/services/api/embassy-api.service.ts
- frontend/projects/ui/src/app/services/api/embassy-mock-api.service.ts
- frontend/projects/ui/src/app/services/api/mock-patch.ts
- frontend/projects/ui/src/app/services/connection.service.ts
- frontend/projects/ui/src/app/services/patch-db/data-model.ts
send marketplace url to server.update
> marketplace url in server.update

- backend/sqlx-data.json
- backend/src/context/rpc.rs
- backend/src/install/cleanup.rs
- backend/src/install/mod.rs
- backend/src/lib.rs
> implement delete-recovered

- backend/src/db/mod.rs
- backend/src/db/model.rs
- backend/src/error.rs
- backend/src/install/mod.rs
> prevents packages from producing conflicting ssl configs

- build/initialization.sh
NO TICKET
these tools are often very useful when helping users debug
> add vim and jq

- backend/src/manager/mod.rs
NO TICKET
goal is to increase stability when a service is in a crash loop.
> handle crash loops better

- backend/src/install/mod.rs
- frontend/projects/ui/src/app/pages/apps-routes/app-list/app-list-rec/app-list-rec.component.ts
- frontend/projects/ui/src/app/services/api/api.types.ts
> add version-priority to installs

- backend/src/bin/embassy-cli.rs
- backend/src/bin/embassy-sdk.rs
- build/00-embassy
> fix `embassy-cli --version` and `embassy-sdk --version`

- backend/src/backup/backup_bulk.rs
- backend/src/context/rpc.rs
- backend/src/disk/mount/filesystem/ecryptfs.rs
> fix backup completion on `unstable`

- frontend/projects/ui/src/app/components/backup-drives/backup-drives.component.html
- frontend/projects/ui/src/app/components/backup-drives/backup-drives.component.ts
NO TICKET
David request to add messaging to backup page if no physical drives appear.
> backup refresh messaging

- index.html
NO TICKET
loading screen to replace nginx
> loading no snake

- build/initialization.sh
this allows ssh'ing in and still allowing the init script to complete
> Move user change early in the process

- backend/src/disk/mount/filesystem/cifs.rs
Fixes issue where cifs would fail to mount a drive on mac properly.
> noserverino

- frontend/projects/ui/src/app/app.component.ts
- frontend/projects/ui/src/app/pages/server-routes/preferences/preferences.page.html
- frontend/projects/ui/src/app/services/api/mock-patch.ts
NO TICKET
make auto check for updates default to enabled
> auto check automatic

- frontend/projects/setup-wizard/src/app/pages/recover/recover.page.ts
> only show attach prompt if product key present

- frontend/projects/ui/src/app/pages/apps-routes/app-show/components/app-show-health-checks/app-show-health-checks.component.html
- frontend/projects/ui/src/app/pages/apps-routes/app-show/components/app-show-health-checks/app-show-health-checks.component.ts
- frontend/projects/ui/src/app/services/api/mock-patch.ts
- frontend/projects/ui/src/app/services/patch-db/data-model.ts
NO TICKET
health check success message
> health check success

- frontend/projects/ui/src/app/components/install-wizard/prebaked-wizards.ts
- frontend/projects/ui/src/app/pages/apps-routes/app-list/app-list-rec/app-list-rec.component.ts
- frontend/projects/ui/src/app/pages/marketplace-routes/marketplace-show/marketplace-show.page.ts
- frontend/projects/ui/src/app/services/api/api.types.ts
NO TICKET
bugfix pass url to install route
> marketplace url install fix

- frontend/projects/diagnostic-ui/src/app/pages/home/home.page.html
- frontend/projects/diagnostic-ui/src/app/pages/home/home.page.ts
https://github.com/Start9Labs/embassy-os/issues/1273
> add details

- CONTRIBUTING.md
- README.md
- build/00-embassy
- frontend/projects/setup-wizard/src/app/pages/recover/recover.page.html
- frontend/projects/setup-wizard/src/app/pages/success/success.page.html
- frontend/projects/ui/src/app/app.component.ts
- frontend/projects/ui/src/app/components/backup-drives/backup-drives.component.html
- frontend/projects/ui/src/app/pages/server-routes/lan/lan.page.html
- frontend/projects/ui/src/app/pages/server-routes/server-show/server-show.page.ts
- frontend/projects/ui/src/app/pages/server-routes/ssh-keys/ssh-keys.page.ts
- frontend/projects/ui/src/app/pages/server-routes/wifi/wifi.page.html
- frontend/projects/ui/src/app/services/error-toast.service.ts
It seems like there ought to be more links than what I found, but perhaps there is just room to add more links going forward.  I will test with this in mind
> Fix links in UI to point to new website

- frontend/projects/ui/src/app/app.component.html
- frontend/projects/ui/src/app/app.component.ts
- frontend/projects/ui/src/app/modals/os-welcome/os-welcome.page.html
- frontend/projects/ui/src/app/modals/snake/snake.page.html
- frontend/projects/ui/src/app/modals/snake/snake.page.ts
- frontend/projects/ui/src/app/pages/marketplace-routes/marketplace.service.ts
NO TICKET
fix snek height issue
> snek height fix

- backend/src/context/setup.rs
- backend/src/setup.rs
this sucks. I know. but it's the lightest touch way to do that. putting up another pr to clean it up, but it may even be best to not merge that until after the release.
addresses #1226
> return SetupResult on setup.complete

- backend/src/manager/mod.rs
and increase startup grace period
> mute crash notifs during shutdown

- frontend/projects/ui/src/app/pages/apps-routes/app-properties/app-properties.page.ts
NO TICKET
Fix back button for properties.  Issue is that back button in properties leaves properties page even if you were nested within properties
> fix back button

- backend/Cargo.lock
- backend/Cargo.toml
- backend/src/marketplace.rs
> handle new content-types from marketplace.get

- backend/src/disk/quirks.rs
testing has shown no issues with UASP on the samsung T7
> whitelist samsung T7

- backend/src/net/nginx.conf.template
- backend/src/nginx/main-ui.conf.template
> allow websockets to containers

- backend/src/disk/quirks.rs
- frontend/projects/ui/src/app/pages/server-routes/kernel-logs/kernel-logs.module.ts
- frontend/projects/ui/src/app/pages/server-routes/kernel-logs/kernel-logs.page.html
- frontend/projects/ui/src/app/pages/server-routes/kernel-logs/kernel-logs.page.ts
- frontend/projects/ui/src/app/pages/server-routes/server-routing.module.ts
- frontend/projects/ui/src/app/pages/server-routes/server-show/server-show.page.ts
- frontend/projects/ui/src/app/services/api/embassy-api.service.ts
- frontend/projects/ui/src/app/services/api/embassy-live-api.service.ts
- frontend/projects/ui/src/app/services/api/embassy-mock-api.service.ts
Frontend component for https://github.com/Start9Labs/embassy-os/pull/1339
Addresses https://github.com/Start9Labs/embassy-os/issues/706
> add kernel log display to server show page

- backend/src/lib.rs
- backend/src/logs.rs
- backend/src/system.rs
- frontend/projects/ui/src/app/pages/server-routes/kernel-logs/kernel-logs.module.ts
- frontend/projects/ui/src/app/pages/server-routes/kernel-logs/kernel-logs.page.html
- frontend/projects/ui/src/app/pages/server-routes/kernel-logs/kernel-logs.page.ts
- frontend/projects/ui/src/app/pages/server-routes/server-routing.module.ts
- frontend/projects/ui/src/app/pages/server-routes/server-show/server-show.page.ts
- frontend/projects/ui/src/app/services/api/embassy-api.service.ts
- frontend/projects/ui/src/app/services/api/embassy-live-api.service.ts
- frontend/projects/ui/src/app/services/api/embassy-mock-api.service.ts
> add endpoint for dmesg logs

- backend/src/bin/embassy-init.rs
- backend/src/diagnostic.rs
- backend/src/disk/fsck.rs
- backend/src/disk/main.rs
- backend/src/disk/mod.rs
- backend/src/setup.rs
> run fsck on startup

- backend/Cargo.lock
- backend/Cargo.toml
> update sqlx directly, and allow patch bumps from other packages

- frontend/projects/marketplace/src/pages/show/package/package.component.html
- frontend/projects/ui/src/app/pages/marketplace-routes/marketplace-show/marketplace-show.page.html
- Fixes display of install button display on service marketplace show page
- Also misc style fixes
> Fix marketplace button display

- backend/Cargo.lock
- backend/Cargo.toml
- backend/src/version/mod.rs
- backend/src/version/v0_3_0_1.rs
- frontend/package-lock.json
- frontend/package.json
- frontend/projects/ui/src/app/modals/os-welcome/os-welcome.page.html
- frontend/projects/ui/src/app/modals/os-welcome/os-welcome.page.scss
- frontend/projects/ui/src/app/services/api/mock-patch.ts
@elvece need a new welcome message for 0.3.0.1
also @MattDHill, does the migration need to *un*ack the welcome message?
> bump version for 0.3.0.1

- backend/src/disk/quirks.rs
- backend/src/version/v0_3_0_1.rs
this causes the disk quirks to be updated during migration to 0.3.0.1
> update quirks during migration

- frontend/config-sample.json
- frontend/projects/marketplace/src/pages/show/about/about.component.html
- frontend/projects/marketplace/src/pages/show/additional/additional.component.html
- frontend/projects/shared/src/types/workspace-config.ts
- frontend/projects/ui/src/app/app.component.html
- frontend/projects/ui/src/app/components/backup-drives/backup.service.ts
- frontend/projects/ui/src/app/components/form-object/form-object.component.scss
- frontend/projects/ui/src/app/components/install-wizard/install-wizard.component.scss
- frontend/projects/ui/src/app/components/install-wizard/notes/notes.component.html
- frontend/projects/ui/src/app/components/install-wizard/notes/notes.component.ts
- frontend/projects/ui/src/app/components/install-wizard/prebaked-wizards.ts
- frontend/projects/ui/src/app/pages/apps-routes/app-list/app-list-rec/app-list-rec.component.ts
- frontend/projects/ui/src/app/pages/server-routes/restore/restore.component.ts
- frontend/projects/ui/src/app/pages/server-routes/server-backup/server-backup.page.ts
- frontend/projects/ui/src/app/services/api/api.fixures.ts
- frontend/projects/ui/src/app/services/api/api.types.ts
- frontend/projects/ui/src/app/services/api/embassy-live-api.service.ts
- frontend/projects/ui/src/app/services/api/embassy-mock-api.service.ts
- frontend/projects/ui/src/app/services/api/mock-patch.ts
- frontend/projects/ui/src/app/services/config.service.ts
- frontend/projects/ui/src/app/services/eos.service.ts
- frontend/projects/ui/src/styles.scss
closes #1364 
Also does better eager loading in general
> better eager loading and better error messaging for backup flow

- backend/src/install/mod.rs
this variable is mislabeled, it is the new manifest, not the previous one.
> fix migrations not running in the `to` block

- frontend/projects/ui/src/app/components/install-wizard/prebaked-wizards.ts
- frontend/projects/ui/src/app/services/api/api.fixures.ts
> dont hang on update and downgrade

- backend/src/manager/health.rs
> attempt to heal when health check passes

- backend/Cargo.lock
- backend/Cargo.toml
- backend/src/version/mod.rs
- backend/src/version/v0_3_0_3.rs
- frontend/package.json
- frontend/projects/ui/src/app/modals/os-welcome/os-welcome.page.html
- frontend/projects/ui/src/app/modals/os-welcome/os-welcome.page.scss
- frontend/projects/ui/src/app/services/api/mock-patch.ts
- system-images/compat/Cargo.lock
@elvece need new welcome page, and any other changes necessary for ui version bump
> version bump

- backend/src/update/mod.rs
> make nicer update sound

- build/README.md
Update README.md to include yq install instructions for Linux
> Update README.md to include yq

- build/README.md
Simplifying and clarifying for first time builders
> ☯️ For the peace of mind ☯️

- CONTRIBUTING.md
Fixed a few broken links and updated the table of contents in the contributing guide
> Fix links in CONTRIBUTING.md, update ToC

- frontend/projects/ui/src/app/pages/server-routes/lan/lan.page.html
- frontend/projects/ui/src/app/pages/server-routes/lan/lan.page.ts
Plus a little bit of refactoring of the component.
Closes #1277
> Link to tor address on LAN setup page (#1277)

- CONTRIBUTING.md
- frontend/README.md
- frontend/package.json
Changes:
- Add syntax highlighting to code blocks
- Make heading casing consistent (see https://github.com/Start9Labs/embassy-os/pull/1463#discussion_r883889676)
- Add marketplace to frontend readme
- change `build:deps` script to use `npm ci` (to make consistent with the [setup instructions](https://github.com/Start9Labs/embassy-os/blob/master/frontend/README.md?plain=1#L35))
> Update contribution and frontend readme

- frontend/projects/shared/styles/shared.scss
- frontend/projects/ui/src/app/app/global/services/update-toast.service.ts
- frontend/projects/ui/src/app/app/snek/snek.directive.ts
- frontend/projects/ui/src/app/components/backup-drives/backup-drives.component.ts
- frontend/projects/ui/src/app/components/logs/logs.page.ts
- frontend/projects/ui/src/app/modals/app-config/app-config.page.ts
- frontend/projects/ui/src/app/modals/app-recover-select/app-recover-select.page.ts
- frontend/projects/ui/src/app/pages/apps-routes/app-actions/app-actions.page.ts
- frontend/projects/ui/src/app/pages/apps-routes/app-show/components/app-show-status/app-show-status.component.ts
- frontend/projects/ui/src/app/pages/developer-routes/developer-list/developer-list.page.ts
- frontend/projects/ui/src/app/pages/developer-routes/developer-menu/developer-menu.page.ts
- frontend/projects/ui/src/app/pages/login/login.page.ts
- frontend/projects/ui/src/app/pages/marketplace-routes/marketplace-list/marketplace-list-content/marketplace-list-content.component.html
- frontend/projects/ui/src/app/pages/marketplace-routes/marketplace-show/marketplace-show.page.html
- frontend/projects/ui/src/app/pages/marketplace-routes/marketplace-status/marketplace-status.component.html
- frontend/projects/ui/src/app/pages/marketplace-routes/marketplace-status/marketplace-status.component.ts
- frontend/projects/ui/src/app/pages/notifications/notifications.page.ts
- frontend/projects/ui/src/app/pages/server-routes/marketplaces/marketplaces.page.ts
- frontend/projects/ui/src/app/pages/server-routes/preferences/preferences.page.ts
- frontend/projects/ui/src/app/pages/server-routes/restore/restore.component.ts
- frontend/projects/ui/src/app/pages/server-routes/server-backup/server-backup.page.ts
- frontend/projects/ui/src/app/pages/server-routes/server-show/server-show.page.ts
- frontend/projects/ui/src/app/pages/server-routes/sessions/sessions.page.ts
- frontend/projects/ui/src/app/pages/server-routes/ssh-keys/ssh-keys.page.ts
- frontend/projects/ui/src/app/pages/server-routes/wifi/wifi.page.ts
- frontend/projects/ui/src/app/services/api/api.fixures.ts
- frontend/projects/ui/src/app/services/api/mock-patch.ts
- frontend/projects/ui/src/app/services/marketplace.service.ts
- frontend/projects/ui/src/app/services/server-config.service.ts
- frontend/projects/ui/src/styles.scss
- Abstracts loader CSS
- Better display of modal and alerts
- Fixes issue with unreadable blue color in logs
- Fixes issue with service updates not displaying properly
> UI cosmetic improvements

- backend/src/net/ssl.rs
> generate unique ca names based off of server id

- backend/build-dev.sh
- backend/build-portable-dev.sh
- backend/build-portable.sh
- backend/build-prod.sh
- system-images/compat/build.sh
a more nuanced approach to #1469
> allow interactive TTY if available

- frontend/projects/shared/styles/shared.scss
- frontend/projects/ui/src/app/components/form-object/form-object.component.scss
- frontend/projects/ui/src/app/pages/apps-routes/app-interfaces/app-interfaces.page.scss
- frontend/projects/ui/src/app/pages/apps-routes/app-properties/app-properties.page.html
- frontend/projects/ui/src/app/pages/server-routes/server-specs/server-specs.page.scss
> Swtich certain inputs and displays to courier for readability

- backend/src/install/update.rs
When trying to recreate locally, noticing that there are locking issues with updating/ uninstalling/ installing some of the packages. 
https://github.com/Start9Labs/embassy-os/issues/1526
This solution is migrating more to the bulk locking, since it was conflicting with locking reasons.
> fix: restart/ uninstall sometimes didn't work

- backend/src/net/tor.rs
> fixes #1169

- backend/src/backup/backup_bulk.rs
- backend/src/control.rs
- backend/src/dependencies.rs
- backend/src/manager/sync.rs
- backend/src/status/mod.rs
backend portion of #368 
this adds a `restarting` status
> add restart rpc and status

- backend/src/backup/backup_bulk.rs
- backend/src/control.rs
- backend/src/dependencies.rs
- backend/src/manager/sync.rs
- backend/src/status/mod.rs
- frontend/projects/ui/src/app/pages/apps-routes/app-show/components/app-show-status/app-show-status.component.html
- frontend/projects/ui/src/app/pages/apps-routes/app-show/components/app-show-status/app-show-status.component.scss
- frontend/projects/ui/src/app/pages/apps-routes/app-show/components/app-show-status/app-show-status.component.ts
- frontend/projects/ui/src/app/services/api/api.types.ts
- frontend/projects/ui/src/app/services/api/embassy-api.service.ts
- frontend/projects/ui/src/app/services/api/embassy-live-api.service.ts
- frontend/projects/ui/src/app/services/api/embassy-mock-api.service.ts
- frontend/projects/ui/src/app/services/patch-db/data-model.ts
- frontend/projects/ui/src/app/services/pkg-status-rendering.service.ts
~~NOTE: do not merge until BE implementation for restart RPC completed~~
> add restart button to service show page and restart rpc api

- libs/artifacts/types.d.ts
While working on the @kn0wmad converting the https://github.com/Start9Labs/bitcoind-wrappe to use the js, had to update the types to match better.
> chore: Update types to match embassyd

- backend/src/install/cleanup.rs
While @chrisguida  was testing he found `Jun 15 17:28:01.330 ERROR patch_db::bulk_locks::unsaturated_args: By counts=0, this phantom type = String is not valid` in the logs. The good news is that this is one of the times that this is not a true error, because an error would be count >= 2
Had to look at all the types and count the stars. Found our outlier that didn't have any stars (where the count comes from).
> fix: found a unsaturaded args fix

- backend/src/config/mod.rs
props to @MattDHill for finding this
> fix dependency/dependent id issue

- backend/src/config/spec.rs
> add textarea to ValueSpecString

- backend/build-prod.sh
- system-images/compat/build.sh
Discovered when doing a totally fresh build on a new ubuntu system ie. super latest shit
> fix backend builds for safe git config

- .gitignore
- backend/sqlx-data.json
- backend/src/auth.rs
- backend/src/control.rs
- backend/src/middleware/auth.rs
- backend/src/setup.rs
- libs/js_engine/src/lib.rs
> add reset password option

- frontend/projects/ui/src/app/pages/server-routes/marketplaces/marketplaces.page.html
- frontend/projects/ui/src/app/pages/server-routes/server-show/server-show.page.ts
- frontend/projects/ui/src/app/pages/server-routes/sessions/sessions.page.html
- frontend/projects/ui/src/app/pages/server-routes/sessions/sessions.page.ts
- frontend/projects/ui/src/app/pages/server-routes/ssh-keys/ssh-keys.page.html
- frontend/projects/ui/src/app/pages/server-routes/wifi/wifi.page.html
- frontend/projects/ui/src/styles.scss
- button to kill all sessions
- session sorting by most recent
- remove ripple effect from button press
- minor copy/css changes
Closes #1485
> kill all sessions and remove ripple effect

- frontend/projects/shared/src/util/misc.util.ts
- frontend/projects/shared/styles/shared.scss
- frontend/projects/ui/src/app/pages/apps-routes/app-show/app-show.page.html
- frontend/projects/ui/src/app/pages/apps-routes/app-show/app-show.page.ts
- frontend/projects/ui/src/app/pages/apps-routes/app-show/pipes/to-buttons.pipe.ts
- frontend/projects/ui/src/app/services/marketplace.service.ts
- frontend/projects/ui/src/app/util/web.util.ts
Tested working via FE proxy to backend.
> adjust service marketplace button for installation source relevance

- backend/src/backup/backup_bulk.rs
- backend/src/db/model.rs
- backend/src/init.rs
- frontend/projects/ui/src/app/app/preloader/preloader.component.ts
- frontend/projects/ui/src/app/components/backup-drives/backup-drives.component.html
- frontend/projects/ui/src/app/components/backup-drives/backup-drives.component.scss
- frontend/projects/ui/src/app/components/backup-drives/backup-drives.component.ts
- frontend/projects/ui/src/app/modals/backup-select/backup-select.module.ts
- frontend/projects/ui/src/app/modals/backup-select/backup-select.page.html
- frontend/projects/ui/src/app/modals/backup-select/backup-select.page.ts
- frontend/projects/ui/src/app/pages/developer-routes/developer-list/developer-list.page.html
- frontend/projects/ui/src/app/pages/server-routes/marketplaces/marketplaces.page.ts
- frontend/projects/ui/src/app/pages/server-routes/server-backup/backing-up/backing-up.component.html
- frontend/projects/ui/src/app/pages/server-routes/server-backup/backing-up/backing-up.component.ts
- frontend/projects/ui/src/app/pages/server-routes/server-backup/server-backup.module.ts
- frontend/projects/ui/src/app/pages/server-routes/server-backup/server-backup.page.html
- frontend/projects/ui/src/app/pages/server-routes/server-backup/server-backup.page.ts
- frontend/projects/ui/src/app/pages/server-routes/server-show/server-show.page.html
- frontend/projects/ui/src/app/services/api/api.fixures.ts
- frontend/projects/ui/src/app/services/api/api.types.ts
- frontend/projects/ui/src/app/services/api/embassy-mock-api.service.ts
- frontend/projects/ui/src/app/services/api/mock-patch.ts
- frontend/projects/ui/src/app/services/eos.service.ts
- frontend/projects/ui/src/app/services/patch-db/data-model.ts
> selective backups and better drive selection interface

- build/initialization.sh
> switch to utc

- backend/src/procedure/docker.rs
this is necessary because *many* old services use io-format yaml for main
> don't crash service if io-format is set for main

- backend/Cargo.lock
- backend/src/procedure/js_scripts.rs
- backend/test/js_action_execute/package-data/scripts/test-package/0.3.0.3/embassy.js
- libs/Cargo.lock
- libs/js_engine/Cargo.toml
- libs/js_engine/src/artifacts/loadModule.js
- libs/js_engine/src/lib.rs
fixes https://github.com/Start9Labs/embassy-os/issues/1602
We have proof that we did the post in our new action, that gets from example.com and does a post to a testing site.
https://webhook.site/#!/b4de0dcb-9715-4c20-aa69-c299913b44ea/d37da3bd-9992-4f9b-8fa6-4cb15324b414/1
> feat: fetch effect

- backend/src/procedure/docker.rs
Potentially I am trying to fix 
And my theory is that since I am no longer consuming the buffer it is going into a state of EOF.
> fix: Closed file

- frontend/projects/ui/src/app/pages/marketplace-routes/marketplace-show/marketplace-show-controls/marketplace-show-controls.component.ts
> fix display of comma between breakages

- build/initialization.sh
- build/write-image.sh
Proper Enable Control Groups for Docker containers #1468
> 🐋 docker stats fix

- build/initialization.sh
https://github.com/Start9Labs/embassy-os/issues/1659
After several reboots, not recreating. Also changing the wifi also i
s fixed
> fix: Resolve fighting with NM

- backend/embassy-init.service
- backend/src/init.rs
- backend/src/version/mod.rs
- backend/src/version/v0_3_1_1.rs
it would be great to find a way to catch this mistake in the type system
basically, the stack overflows because it does not know how to find a way back to the current migration
made a change to turn this into a descriptive error
> fix migration, add logging

- backend/src/bin/embassy-init.rs
- backend/src/init.rs
- backend/src/shutdown.rs
> add standby mode

- frontend/projects/diagnostic-ui/src/app/pages/logs/logs.page.ts
- frontend/projects/shared/src/public-api.ts
- frontend/projects/shared/src/util/to-local-iso-string.ts
- frontend/projects/ui/src/app/app/preloader/preloader.component.html
- frontend/projects/ui/src/app/components/logs/logs.page.ts
- frontend/projects/ui/src/app/pages/apps-routes/app-list/app-list-reorder/app-list-reorder.component.html
- frontend/projects/ui/src/app/pages/apps-routes/app-properties/app-properties.page.html
- frontend/projects/ui/src/app/pages/notifications/notifications.page.html
- frontend/projects/ui/src/app/pages/notifications/notifications.page.ts
- frontend/projects/ui/src/app/pipes/mask/mask.pipe.ts
- frontend/projects/ui/src/app/services/api/api.fixures.ts
> 0312 multiple FE

- frontend/projects/setup-wizard/src/app/services/api/http.service.ts
- frontend/projects/ui/src/app/services/http.service.ts
observe response not events in http reqs to effectively use firstValueFrom
> Fix http requests

- backend/src/init.rs
- build/initialization.sh
Fixes https://docs.syncthing.net/users/faq.html#inotify-limits for
https://github.com/Start9Labs/syncthing-wrapper/issues/17
Using the notify of 2^20,
> fix: Add modification to the max_user_watches

- frontend/projects/ui/src/app/pages/apps-routes/app-actions/app-actions.page.ts
- frontend/projects/ui/src/app/pages/apps-routes/app-list/app-list.page.ts
- frontend/projects/ui/src/app/pages/apps-routes/app-show/components/app-show-menu/app-show-menu.component.html
- frontend/projects/ui/src/app/pages/apps-routes/app-show/components/app-show-menu/app-show-menu.component.scss
- frontend/projects/ui/src/app/pages/apps-routes/app-show/components/app-show-menu/app-show-menu.component.ts
- frontend/projects/ui/src/app/pages/apps-routes/app-show/pipes/to-buttons.pipe.ts
- frontend/projects/ui/src/app/services/api/mock-patch.ts
- frontend/projects/ui/src/app/services/patch-db/data-model.ts
- frontend/projects/ui/src/app/util/get-server-info.ts
- frontend/projects/ui/src/app/util/parse-data-model.ts
> highlight instructions if not viewed

- build/init-with-sound.sh
- build/initialization.service
- build/initialization.sh
- build/write-image.sh
apparently `set -e` doesn't work in subshells
> fix init to exit on failure

- backend/src/net/nginx.rs
> fix: Bad cert of *.local.local is now fixed to correct.

- .github/workflows/product.yaml
- Makefile
- backend/src/init.rs
- backend/src/net/dns.rs
- backend/src/version/v0_3_2.rs
- build/initialization.sh
- build/write-image.sh
- system-images/binfmt/.gitignore
- system-images/binfmt/Dockerfile
- system-images/binfmt/Makefile
- system-images/compat/Cargo.lock
- system-images/compat/Makefile
this should fix DNS issues, as well as not rely on daemons during initialization
> restructure initialization

- frontend/projects/ui/src/app/components/logs/logs.component.ts
- frontend/projects/ui/src/app/pages/apps-routes/app-logs/app-logs.page.html
- frontend/projects/ui/src/app/pages/server-routes/kernel-logs/kernel-logs.page.html
- frontend/projects/ui/src/app/pages/server-routes/server-logs/server-logs.page.html
> give name to logs file

- frontend/projects/ui/src/app/pages/server-routes/lan/lan.page.html
- frontend/projects/ui/src/app/pages/server-routes/lan/lan.page.ts
> allow ca download over lan

- frontend/projects/ui/src/app/components/backup-drives/backup-drives.component.html
- frontend/projects/ui/src/app/modals/app-recover-select/app-recover-select.page.html
- frontend/projects/ui/src/app/modals/app-recover-select/app-recover-select.page.scss
> remove restore warning and better messaging for backup/restore

- frontend/projects/diagnostic-ui/src/app/pages/home/home.page.ts
- frontend/projects/ui/src/app/pages/server-routes/server-show/server-show.page.ts
Typo fix "loosing" -> "losing"
> Minor typo fixes

- backend/src/manager/mod.rs
- backend/src/procedure/docker.rs
- backend/src/procedure/mod.rs
- backend/src/s9pk/reader.rs
Given health 
```yaml
test:
name: Sync Test
success-message: Testing
type: docker
image: main
system: false
entrypoint: sh
args: ["/usr/bin/health.sh"]
mounts: {}
io-format: yaml
inject: true
```
And the shell command is using something that will only work if it is injected into the system that the Syncthing is running.
> wip: Making Injectable exec

- backend/src/manager/mod.rs
> silence service crash notifications

- backend/src/auth.rs
- backend/src/backup/backup_bulk.rs
- backend/src/context/cli.rs
- backend/src/context/rpc.rs
- backend/src/context/setup.rs
- backend/src/setup.rs
- frontend/projects/install-wizard/src/app/pages/home/home.page.ts
- frontend/projects/ui/src/app/components/backup-drives/backup-drives.component.ts
- frontend/projects/ui/src/app/components/widget-list/widget-list.component.ts
- frontend/projects/ui/src/app/pages/apps-routes/app-show/app-show.page.html
- frontend/projects/ui/src/app/pages/apps-routes/app-show/app-show.page.ts
- frontend/projects/ui/src/app/pages/login/login.page.ts
- frontend/projects/ui/src/app/pages/marketplace-routes/marketplace-list/marketplace-list.page.html
- frontend/projects/ui/src/app/pages/marketplace-routes/marketplace-list/marketplace-list.page.scss
- frontend/projects/ui/src/app/pages/marketplace-routes/marketplace-list/marketplace-list.page.ts
- frontend/projects/ui/src/app/pages/server-routes/lan/lan.page.html
- frontend/projects/ui/src/app/pages/server-routes/server-show/server-show.page.html
- frontend/projects/ui/src/app/pages/server-routes/server-show/server-show.page.ts
- frontend/projects/ui/src/app/pages/server-routes/wifi/wifi.page.ts
- frontend/projects/ui/src/app/services/api/api.types.ts
- frontend/projects/ui/src/app/services/api/embassy-api.service.ts
- frontend/projects/ui/src/app/services/api/embassy-live-api.service.ts
- frontend/projects/ui/src/app/services/api/embassy-mock-api.service.ts
- frontend/projects/ui/src/app/services/config.service.ts
> get pubkey and encrypt password on login

- backend/src/backup/mod.rs
- backend/src/backup/restore.rs
- backend/src/install/mod.rs
- backend/src/update/mod.rs
> restore interfaces before creating manager

- backend/src/logs.rs
> fix websocket hangup error

- build/lib/scripts/check-monitor
- build/lib/scripts/enable-kiosk
- build/raspberry-pi/initialization.sh
Also disables kiosk mode on the Pi
> wait for monitor to be attached before launching firefox

- backend/src/control.rs
- backend/src/install/mod.rs
https://user-images.githubusercontent.com/2364004/205457039-4e95a61d-eb61-4afe-be9e-8305ef9c6a3e.mp4
> fix: Stop service before

- backend/src/backup/restore.rs
- backend/src/backup/target/mod.rs
- backend/src/setup.rs
https://user-images.githubusercontent.com/2364004/205516368-1d10dd20-7572-432f-86f1-2e50c35ef1ff.mp4
> fix: Cifs not working because rw

- backend/src/backup/restore.rs
Trying to fix the error seen in here with timeouts
> fix: Make the restores limited # restore at a time

- backend/src/init.rs
this prevents logs from growing past 1GB when machine id changes
> delete logs from other machine ids

- backend/src/bin/embassy-init.rs
- backend/src/shutdown.rs
> only do standby mode for pi

- frontend/projects/setup-wizard/src/app/modals/password/password.page.html
- frontend/projects/ui/src/app/components/connection-bar/connection-bar.component.html
- frontend/projects/ui/src/app/services/api/api.fixures.ts
- frontend/projects/ui/src/app/services/form.service.ts
> fix config bug for number 0 and also maybe conenction icon

- backend/src/version/mod.rs
- backend/src/version/v0_3_3_1.rs
- frontend/patchdb-ui-seed.json
- frontend/projects/marketplace/src/types.ts
- frontend/projects/ui/src/app/app/preloader/preloader.component.ts
- frontend/projects/ui/src/app/pages/marketplace-routes/marketplace-show/marketplace-show.page.html
- frontend/projects/ui/src/app/services/api/api.fixures.ts
- frontend/projects/ui/src/app/services/patch-db/data-model.ts
~~Waiting on Registry changes~~ completed by @elvece
> re-add community marketplace and handle missing dependency

- frontend/config-sample.json
- frontend/projects/shared/src/types/workspace-config.ts
- frontend/projects/ui/src/app/modals/marketplace-settings/marketplace-settings.page.ts
- frontend/projects/ui/src/app/pages/updates/updates.page.ts
- frontend/projects/ui/src/app/services/marketplace.service.ts
closes #2131
Also fixes a bug with community marketplace index
> Only show alpha and beta in updates with dev tools enabled

- frontend/projects/ui/src/app/pages/server-routes/wifi/wifi.module.ts
- frontend/projects/ui/src/app/pages/server-routes/wifi/wifi.page.html
- frontend/projects/ui/src/app/pages/server-routes/wifi/wifi.page.scss
- frontend/projects/ui/src/app/pages/server-routes/wifi/wifi.page.ts
- frontend/projects/ui/src/app/pages/server-routes/wifi/wifiSpec.ts
- frontend/projects/ui/src/app/services/api/api.types.ts
- frontend/projects/ui/src/app/services/api/embassy-api.service.ts
- frontend/projects/ui/src/app/services/api/embassy-live-api.service.ts
- frontend/projects/ui/src/app/services/api/embassy-mock-api.service.ts
- frontend/projects/ui/src/app/services/api/mock-patch.ts
- frontend/projects/ui/src/app/services/patch-db/data-model.ts
> Wifi optional

- backend/src/db/model.rs
- backend/src/lib.rs
- backend/src/system.rs
- frontend/projects/ui/src/app/app/preloader/preloader.component.ts
- frontend/projects/ui/src/app/pages/server-routes/experimental-features/experimental-features.module.ts
- frontend/projects/ui/src/app/pages/server-routes/experimental-features/experimental-features.page.html
- frontend/projects/ui/src/app/pages/server-routes/experimental-features/experimental-features.page.ts
- frontend/projects/ui/src/app/pages/server-routes/server-routing.module.ts
- frontend/projects/ui/src/app/pages/server-routes/server-show/server-show.page.ts
- frontend/projects/ui/src/app/services/api/api.types.ts
- frontend/projects/ui/src/app/services/api/embassy-api.service.ts
- frontend/projects/ui/src/app/services/api/embassy-live-api.service.ts
- frontend/projects/ui/src/app/services/api/embassy-mock-api.service.ts
- frontend/projects/ui/src/app/services/api/mock-patch.ts
- frontend/projects/ui/src/app/services/patch-db/data-model.ts
- libs/models/src/errors.rs
Adds experimental features to system tab. User can now reset Tor and enable/disable zram
> experimental features for zram and reset tor

- frontend/projects/ui/src/app/components/widget-list/widget-list.component.ts
- frontend/projects/ui/src/app/pages/marketplace-routes/marketplace-list/marketplace-list.page.ts
- frontend/projects/ui/src/app/pages/server-routes/server-show/server-show.page.ts
Minor typo fixes and change contact links to reflect move to start9.com/contact
> maint/minor UI typo fixes

- Makefile
- backend/Cargo.toml
- backend/README.md
- backend/build-prod.sh
- backend/src/disk/mount/filesystem/cifs.rs
- backend/src/net/mod.rs
- backend/src/net/net_controller.rs
- compress-uis.sh
So the issue is that the new build system for a single binary won't work in the mac because there is no avahi tools.
> Fixes: Builds for the macs

- backend/src/bins/start_init.rs
- build/lib/scripts/postinst
- build/lib/scripts/tor-check.sh
> Add tor-check to CLI

- README.md
> add apollo review badge and update badges with icons

- backend/.sqlx/query-b203820ee1c553a4b246eac74b79bd10d5717b2a0ddecf22330b7d531aac7c5d.json
- backend/src/install/cleanup.rs
> cleanup network keys on uninstall

- backend/src/volume.rs
> fix js backups

- sdk/lib/exver/index.ts
- Add fns to `incrementMajor` and `incrementMinor`.
- Complete `satisfiedBy` fn
> complete satisfiedBy fn

- build/dpkg-deps/depends
- core/startos/src/s9pk/v2/pack.rs
ref https://github.com/plougher/squashfs-tools/issues/285
> fix uid mapping in squashfs's made from tarballs

- sdk/lib/util/SubContainer.ts
Actions where running in a race condition that they sometimes didn't wait for the container to be started and the issue was the exec that was then run after would have an issue.
> fix: Container runtime actions

- sdk/package/lib/util/SubContainer.ts
> Fix: Error Messages in HealthCheck

- sdk/package/lib/util/fileHelper.ts
> Feat: With path

- container-runtime/src/Adapters/RpcListener.ts
- container-runtime/src/Adapters/Systems/SystemForStartOs.ts
> fix: Actions like the action don't give the results

- core/startos/src/registry/os/asset/get.rs
There was a mismatch between the documentation and the behavior of this command. The implementation has been modified to match the docs
> download to directory not filename

- container-runtime/src/Adapters/Systems/SystemForEmbassy/index.ts
- package-lock.json
- web/projects/ui/src/app/services/api/api.fixures.ts
[#2756 [bug] Dependency not showing as dependnency ](https://github.com/Start9Labs/start-os/issues/2756)
Here we have the mempool
and this time I can finally click on the mempool and we no longer have the issues seen
> fix: Dependency

- core/startos/Cargo.toml
- core/startos/src/net/web_server.rs
this is very difficult to reliably reproduce, so a lot more testing will be needed before claiming this is fixed
> attempt to fix webserver lockup

- sdk/base/lib/util/GetSystemSmtp.ts
- sdk/base/lib/util/getServiceInterface.ts
- sdk/base/lib/util/getServiceInterfaces.ts
- sdk/package/lib/health/HealthCheck.ts
- sdk/package/lib/store/getStore.ts
- sdk/package/lib/util/GetSslCertificate.ts
- sdk/package/lib/util/fileHelper.ts
- delete keys with explicit { foo: undefined } in file helper
- add id to HealthCheck.of
- add onChange as an alternative to *watch in all cases
- update comments
> minor sdk tweaks

- container-runtime/package-lock.json
- container-runtime/src/Adapters/EffectCreator.ts
- container-runtime/src/Adapters/RpcListener.ts
- container-runtime/src/Models/CallbackHolder.ts
- core/startos/src/service/action.rs
- sdk/base/lib/actions/index.ts
- sdk/package/lib/mainFn/Daemon.ts
- sdk/package/lib/util/fileHelper.ts
- sdk/package/package-lock.json
- sdk/package/package.json
> add transformers to file helpers

- core/startos/src/action.rs
> upcast v0 action results to v1

- web/projects/ui/src/app/routes/portal/routes/marketplace/modals/preview.component.ts
- web/projects/ui/src/app/utils/get-package-data.ts
> fix: extract correct manifest in updating state
